"""The generic, nestable acquisition method and its bindable components.

``Episode`` owns the method loop and tree. Surfaces compose sources, leaves,
result projections, controller functions, compact nested messages, and
post-controller hooks around it.
"""

from .runtime import Controller, ControllerFactory, ControllerRuntime, Path, Scope
from .communication import ParentReport, ReportContract
from .binding import (
    EpisodeBindingDeclaration,
    EpisodeChildSlot,
    EpisodeControllerBinding,
    EpisodeFunctionBinding,
    EpisodeTopologyRole,
)
from .identities import (
    EpisodeRef,
    StructuralPath,
    UnitRef,
    normalize_structural_path,
)
from .episode import (
    END_EXHAUSTED,
    END_INCOMPLETE,
    END_SOURCE_FAILED,
    END_YIELD_STOP,
    SOURCE_END_KINDS,
    SOURCE_END_REASONS,
    Acquirable,
    ChildEpisodeUnit,
    ClosedRecord,
    Context,
    Contribution,
    Episode,
    EpisodeCompletion,
    EpisodeGoal,
    GoalPreview,
    GoalProposal,
    GoalState,
    EpisodeRecord,
    EpisodeRequest,
    EpisodeTree,
    EpisodeUpdate,
    EpisodeView,
    EpochMutation,
    Grain,
    Leaf,
    ResumeUnit,
    SourceEnd,
    UnitRecord,
    UnitSource,
    UnitView,
    leaves,
)

__all__ = [
    "ParentReport",
    "ReportContract",
    "Path",
    "Scope",
    "Controller",
    "ControllerFactory",
    "ControllerRuntime",
    "EpisodeBindingDeclaration",
    "EpisodeChildSlot",
    "EpisodeControllerBinding",
    "EpisodeFunctionBinding",
    "EpisodeTopologyRole",
    "EpisodeRef",
    "StructuralPath",
    "UnitRef",
    "normalize_structural_path",
    "END_EXHAUSTED",
    "END_INCOMPLETE",
    "END_SOURCE_FAILED",
    "END_YIELD_STOP",
    "SOURCE_END_KINDS",
    "SOURCE_END_REASONS",
    "Acquirable",
    "ChildEpisodeUnit",
    "ClosedRecord",
    "Context",
    "Contribution",
    "Episode",
    "EpisodeCompletion",
    "EpisodeGoal",
    "GoalPreview",
    "GoalProposal",
    "GoalState",
    "EpisodeRecord",
    "EpisodeRequest",
    "EpisodeTree",
    "EpisodeUpdate",
    "EpisodeView",
    "EpochMutation",
    "Grain",
    "Leaf",
    "ResumeUnit",
    "SourceEnd",
    "UnitRecord",
    "UnitSource",
    "UnitView",
    "leaves",
]
